services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - backend-server

  backend-server:
    build:
      context: .
      dockerfile: ./docker/backend-server-py.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
