services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
      args:
        VITE_API_URL: ws://localhost:8082
    ports:
      - "80:80"
    networks:
      - webnet

  backend-server:
    build:
      context: .
      dockerfile: ./docker/backend-server-py.Dockerfile
    ports:
      - "8082:8080"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
