version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - backend-server-rs

  backend-server-rs:
    build:
      context: .
      dockerfile: ./docker/backend-server-rs.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
