[package]
name = "backend-server-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0"
actix-http = "3.9.0"
actix-web-actors = "4.3.1"
serde = "1.0.210"
serde_json = "1.0.128"
env_logger = "0.11.5"
log = "0.4.22"