name: Backend Python Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the docker image
      run: docker build . --file docker/backend-server-py.Dockerfile --tag backend-server-py
    - name: Run the docker image
      run: docker run -d --name backend-server-py -p 8080:8080 backend-server-py
    - name: Test WebSocket Connection
      run: |
        curl -H "Upgrade: websocket" -H "Connection: Upgrade" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" ws://localhost:8080 || exit 1
