name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the docker image
      run: docker build . --file docker/backend-server-rs.Dockerfile --tag backend-server-rs
    - name: Run the docker image
      run: docker run -d --name backend-server-rs -p 8081:8080 backend-server-rs
    # - name: Sleep until server is ready
    #   run: sleep 5s
    - name: Test WebSocket Connection
      run: |
        curl -H "Upgrade: websocket" -H "Connection: Upgrade" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" http://localhost:8080/ws || exit 1
